repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: (migrations/|tests/)
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args: [--remove]
        exclude: (migrations/|tests/)
      - id: detect-private-key
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        always_run: false
        args: [--line-length=120]
        exclude: (migrations/|reports/)
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      - id: ruff
        #args: [--fix]
        exclude: (migrations/|tests/)
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.10
    hooks:
      - id: uv-lock
      - id: uv-export
default_language_version:
  python: python3.12
