version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    image: postgres:latest
    container_name: pg_template
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - ./.envs/.env-postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
        - "local-development"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_template
    env_file:
      - ./.envs/.env-server-email
    ports:
      - "${MAILHOG_PORT_1}:8025"
      - "${MAILHOG_PORT_2}:1025"
    networks:
      - "local-development"

  admin:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: local_admin_template
    container_name: local_admin_template
    links:
      - postgres:postgres
    working_dir: /app
    volumes:
      - type: bind
        source: ./src
        target: /app
    env_file:
      - ./.envs/.env
      - ./.envs/.env-postgres
    environment:
      - DJANGO_SETTINGS_MODULE=settings.admin.local
      - DJANGO_PORT=8001
    ports:
      - "${APP_ADMIN_PORT}:8001"
    command: /start
    depends_on:
      - mailhog
    networks:
      - "local-development"

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: local_admin_template
    container_name: local_admin_template
    links:
      - postgres:postgres
      - mailhog
    working_dir: /app
    volumes:
      - type: bind
        source: ./src
        target: /app
    env_file:
      - ./.envs/.env
      - ./.envs/.env-postgres
    environment:
      - DJANGO_SETTINGS_MODULE=settings.api.local
      - DJANGO_PORT=8002
    ports:
      - "${APP_API_PORT}:8002"
    command: /start
    networks:
      - "local-development"
    depends_on:
      - mailhog
networks:
  local-development:
