version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

networks:
  local-development:

services:
  postgres:
    extends:
      file: compose/service.postgres.yml
      service: postgres
    ports:
      - "5435:5432"
    networks:
      - "local-development"
    env_file:
      - ./.envs/${ENVIRONMENT}/postgres.env

  bash:
    extends:
      file: compose/service.app.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=settings.api.local
      - DJANGO_CONFIGURATION=LocalConfig
      - DJANGO_ROOT_URLCONF=urls.api
    links:
      - postgres:postgres
    ports:
      - "9000:9000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
