volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

networks:
  local-development:


services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ${BASE_DIR}/environments/${ENVIRONMENT}/.env-postgresql
    networks:
      - local-development
  app:
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile-local
    stdin_open: true # For ipdb
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /app
    command: /start
    restart: always
    links:
      - postgres:postgres
    env_file:
      - ${BASE_DIR}/environments/${ENVIRONMENT}/${APP_TYPE}/.env-django
      - ${BASE_DIR}/environments/${ENVIRONMENT}/.env-postgresql
    environment:
      DJANGO_SETTINGS_MODULE: settings.admin.env_local
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - "local-development"
  bash:
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile-local
    links:
      - postgres:postgres
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - type: bind
        source: ./src
        target: /app
